### ISSUE TITLE
Gronkh.tv Stream Archive Fehler

### ISSUE THREAD

**Issue by G-XVI** [Popelschnipser/plugin.video.gronkhtvarchive#2]
Die Liste der Vergangene Streams ist ab Heute nicht mehr aufrufbar.

**Comment by G-XVI** [comment]
2022-01-22 19:06:13.132 T:9313    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.gronkhtvarchive/addon.py", line 370, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.gronkhtvarchive/addon.py", line 346, in router
                                                       all_streams_menu(params["page"])
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.gronkhtvarchive/addon.py", line 275, in all_streams_menu
                                                       create_streamlist(all_streams, sorted_episodes, "Vergangene Streams", str(page))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.gronkhtvarchive/addon.py", line 298, in create_streamlist
                                                       title = get_stream_title(all_streams_dict, episode)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.gronkhtvarchive/addon.py", line 58, in get_stream_title
                                                       return stream_dict[episode]["title"].split(" - ", 1)[1]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2022-01-22 19:06:13.414 T:9313     INFO <general>: Python interpreter stopped
2022-01-22 19:06:13.429 T:9312    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.gronkhtvarchive/?action=listing&category=Vergangene%20Streams&page=0
2022-01-22 19:06:13.431 T:9076    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.gronkhtvarchive/?action=listing&category=Vergangene%20Streams&page=0) failed

**Comment by Popelschnipser** [comment]
Danke fürs Melden des Fehlers. Der Aufbau der Streamtitel wurde scheinbar geändert, wodurch nach einem Split-Befehl auf einen Index zugegriffen werden sollte, den es nicht gab.
Der Fehler sollte jetzt behoben sein, indem jetzt geprüft wird, ob es diesen Index auch tatsächlich gibt. 
Bei mir funktioniert es (Kodi 18.7). Bitte prüfen, ob alles klappt, dann würde ich diesen Issue schließen.

**Comment by G-XVI** [comment]
Besten Dank für das rasche fixen des Scriptes. :)

Ich habe es nun auf Kodi 19.3 auch erfolgreich testen können. Funktioniert wieder einwandfrei.

Nun kann ich jetzt vor dem einschlafen noch ne schöne Gronkh Folge zu Ende schauen. ^^

**Comment by Popelschnipser** [comment]
Gern geschehen. Und gut zu wissen, dass außer mir noch weitere Leute mein Addon nutzen 😂 

Ich werde mich außerdem die Tage nochmal dran setzen, um die Ladezeiten etwas zu optimieren. Es dauert mir doch etwas zu lange, bis die Liste mit den letzten Streams geladen ist.
